name: Simple Android Build Test

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: List files
      run: |
        echo "Files in repository:"
        ls -la
        echo "Content of buildozer.spec:"
        cat buildozer.spec || echo "buildozer.spec not found"
        echo "Looking for main.py:"
        ls -la *.py || echo "No Python files found"
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        
    - name: Test buildozer
      run: |
        buildozer --version
        echo "Buildozer installed successfully"
